# This file is for adding themes to your GitHub Pages Site
name: m4ndyf3y GitHub Site
remote_theme: pages-theme/Cayman@v0.2.0
plugins_dir: 
- jekyll-remote-theme # add this to the plugins list if you already have one

